#!/usr/bin/env bash

SCRIPT=`realpath $0`
SCRIPTPATH=`dirname $SCRIPT`
PARENTPATH=`dirname $SCRIPTPATH`

# include init
source $PARENTPATH/.common-init.sh

# to abort the script if any command returns a failure (nonzero) status
set -e
# script will exit with error when variable not set
set -u # or set -o nounset

function post_docker_start() {
    local container="$1"
    # custom implementation
    printf 'Starting up pihole container '
    for i in $(seq 1 60); do
        if [ "$(docker inspect -f "{{.State.Health.Status}}" $container)" == "healthy" ] ; then
            printf ' OK'
            if docker logs $container 2> /dev/null | grep 'password:'; then
                echo -e "\n$(docker logs pihole 2> /dev/null | grep 'password:') for your pi-hole: http://${ServerIP}/admin/"
            else
                echo -e "\nAdmin webpage: http://${ServerIP}/admin/"
            fi
            exit 0
        else
            sleep 3
            printf '.'
        fi
    done;
    echo -e "\nTimed out waiting for Pi-hole start, check your container logs for more info (\`$0 log\`)"
    exit 1
}

# due to set -u we need to define a default value of empty when no arguments are passed
# https://stackoverflow.com/questions/43707685/set-u-nounset-vs-checking-whether-i-have-arguments
case "${1-}" in
###########################################################
# PUT HERE SPECIFIC CONTAINER FUNCTIONALITY - start       #
###########################################################
chpasswd)
    echo -e "Changing admin password for $CONTAINER\n"
    docker exec -it $CONTAINER pihole -a -p
    exit $?
    ;;

###########################################################
# PUT HERE SPECIFIC CONTAINER FUNCTIONALITY - end         #
###########################################################
*)
    # include common operations
    source $PARENTPATH/.common-operations.sh
    echo -e "\n----------------------------------------"
    exit 2
    ;;
esac
exit 0
