#!/usr/bin/env bash

# include init
source $(realpath $0 | xargs dirname | xargs dirname)/.common-init.sh

function pre_docker_create() {
    ## if is a folder path, chech if exists
    #if [[ "$VOL_ETC_OPENVPN" == *"/"* ]]; then
    #    echo -e "Container data is a folder: $VOL_ETC_OPENVPN"
    #    if [[ ! -e "$VOL_ETC_OPENVPN" ]]; then
    #        mkdir -p "$VOL_ETC_OPENVPN"
    #        # chgrp $DOCKER_GROUP $VOL_ETC_OPENVPN
    #    fi
    #else
    #    echo -e "Container data is a docker volume: $VOL_ETC_OPENVPN"
    #fi
}

# due to set -u we need to define a default value of empty when no arguments are passed
# https://stackoverflow.com/questions/43707685/set-u-nounset-vs-checking-whether-i-have-arguments
case "${1-}" in
###########################################################
# PUT HERE SPECIFIC CONTAINER FUNCTIONALITY - start       #
###########################################################
init)
    echo -e "---------------------------------\n"
    echo -e "Init container $CONTAINER\n"
    echo -e "---------------------------------\n"
    # TODO: create docker volume if necessary
    echo -e "Initialize $CONTAINER configuration\n"
    docker run -v $VOL_ETC_OPENVPN:/etc/openvpn --log-driver=none --rm $IMAGE ovpn_genconfig -u udp://$OVPN_DOMAIN -n $OVPN_DNS_SERVER1 -n $OVPN_DNS_SERVER2 -n $OVPN_DNS_SERVER3
    docker run -v $VOL_ETC_OPENVPN:/etc/openvpn --log-driver=none --rm -it $IMAGE ovpn_initpki
    exit $?
    ;;
fix-permissions)
    echo -e "---------------------------------\n"
    echo -e "---------------------------------\n"
    # if is a folder path, chech if exists
    if [[ "$VOL_ETC_OPENVPN" == *"/"* ]]; then
        echo -e "Container data is a folder: $VOL_ETC_OPENVPN"
        if [[ -e "$VOL_ETC_OPENVPN" ]]; then
            sudo chown -R $(whoami) "$VOL_ETC_OPENVPN"
            sudo chgrp -R "$DOCKER_GROUP" "$VOL_ETC_OPENVPN"
        fi
    else
        echo -e "Container data is a docker volume: $VOL_ETC_OPENVPN"
    fi

    ;;
gene-client-nopass|generate-client)
    echo -e "---------------------------------\n"
    if [[ "$1" == *"-nopass" ]]; then
        echo -e "Generate a client certificate without a passphrase"
    else
        echo -e "Generate a client certificate"
    fi
    echo -e "---------------------------------\n"
    echo -e "---------------------------------\n"
    echo -e "Enter client username: "

    read CLIENTNAME

    if [[ ! "$CLIENTNAME" == "" ]]; then
        if [[ "$1" == *"-nopass" ]]; then
            docker run -v $VOL_ETC_OPENVPN:/etc/openvpn --log-driver=none --rm -it $IMAGE easyrsa build-client-full $CLIENTNAME nopass
        else
            docker run -v $VOL_ETC_OPENVPN:/etc/openvpn --log-driver=none --rm -it $IMAGE easyrsa build-client-full $CLIENTNAME
        fi
    else
        echo -e "\nMust provide a non empty username"
    fi
    exit $?
    ;;
revolient-remove|revoke-client)
    echo -e "---------------------------------\n"
    if [[ "$1" == *"-remove" ]]; then
        echo -e "Revoking a client certificate (REMOVE)"
    else
        echo -e "Revoking a client certificate"
    fi
    echo -e "---------------------------------\n"
    echo -e "---------------------------------\n"
    echo -e "Enter client username: "

    read CLIENTNAME

    if [[ ! "$CLIENTNAME" == "" ]]; then
        if [[ "$1" == *"-remove" ]]; then
            docker run -v $VOL_ETC_OPENVPN:/etc/openvpn --log-driver=none --rm -it $IMAGE ovpn_revokeclient $CLIENTNAME remove
        else
            docker run -v $VOL_ETC_OPENVPN:/etc/openvpn --log-driver=none --rm -it $IMAGE ovpn_revokeclient $CLIENTNAME
        fi
    else
        echo -e "\nMust provide a non empty username"
    fi
    exit $?
    ;;
retr-client-config)
    echo -e "---------------------------------\n"
    echo -e "Retrieve a client configuration with embedded certificates"
    echo -e "---------------------------------\n"
    echo -e "---------------------------------\n"
    echo -e "Enter client username: "

    read CLIENTNAME

    if [[ ! "$CLIENTNAME" == "" ]]; then
        docker run -v $VOL_ETC_OPENVPN:/etc/openvpn --log-driver=none --rm -it $IMAGE ovpn_getclient $CLIENTNAME > $CLIENTNAME.ovpn
    else
        echo -e "\nMust provide a non empty username"
    fi
    exit $?
    ;;
###########################################################
# PUT HERE SPECIFIC CONTAINER FUNCTIONALITY - end         #
###########################################################
*)
    # include common operations
    source $PARENTPATH/.common-operations.sh
    echo -e "\t\t\t\t----------------------------------------
                                 init
                                 fix-permissions
                                 generate-client-nopass | generate-client
                                 revoke-client-remove | revoke-client
                                 retrieve-client-config"
    ;;
esac
exit 0
