#!/usr/bin/env bash

# include init
source $(realpath $0 | xargs dirname | xargs dirname)/.common-init.sh

# due to set -u we need to define a default value of empty when no arguments are passed
# https://stackoverflow.com/questions/43707685/set-u-nounset-vs-checking-whether-i-have-arguments
case "${1-}" in
###########################################################
# PUT HERE SPECIFIC CONTAINER FUNCTIONALITY - start       #
###########################################################
check-permission)
    echo "---------------------------------"
    echo "Check write permissions: $DEVICE "
    echo "---------------------------------"
    test -w $DEVICE && echo "OK: user/group has write permissions" || echo "FAILED: user/group doesn't have write permissions"
    exit 0
    ;;
set-defaults|force-defaults)
    echo -e "---------------------------------\n"
    echo -e "Setting defaults for $CONTAINER\n"
    echo -e "---------------------------------\n"

    $0 create-folder-structure

    file_path="$VOL_DATA/configuration.yaml"
    [[ -e "$file_path" && "$1" == "set-defaults" ]] || echo "overwriting: $file_path" && \
    cat << EOF > $file_path
homeassistant: false
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://${CONTAINER_PREFIX}-mosquitto'
  user: user
  password: password
  version: 5
serial:
  port: $DEVICE
advanced:
  rtscts: false
  log_level: info
  pan_id: 6755
device_options: {}
external_converters: []
EOF
#############################################################
    ;;
###########################################################
# PUT HERE SPECIFIC CONTAINER FUNCTIONALITY - end         #
###########################################################
*)
    # include common operations
    source $PARENTPATH/.common-operations.sh
    echo -e "\t\t\t\t----------------------------------------
                                 check-permission
                                 set-defaults | force-defaults
                                 "
    ;;
esac
exit 0
