#!/usr/bin/env bash

# include init
source $(realpath $0 | xargs dirname | xargs dirname)/.common-init.sh

# due to set -u we need to define a default value of empty when no arguments are passed
# https://stackoverflow.com/questions/43707685/set-u-nounset-vs-checking-whether-i-have-arguments
case "${1-}" in
###########################################################
# PUT HERE SPECIFIC CONTAINER FUNCTIONALITY - start       #
###########################################################
users)
    echo -e "---------------------------------\n"
    echo -e "Execute command for container $CONTAINER\n"
    echo -e "---------------------------------\n"
    docker exec -it $CONTAINER /app/show-peer ${PEERS/,/ }
    exit $?
    ;;
user)
    echo -e "---------------------------------\n"
    echo -e "Execute command for container $CONTAINER\n"
    echo -e "---------------------------------\n"
    docker exec -it $CONTAINER /app/show-peer ${2-}
    exit $?
    ;;
###########################################################
# PUT HERE SPECIFIC CONTAINER FUNCTIONALITY - end         #
###########################################################
*)
    # include common operations
    source $PARENTPATH/.common-operations.sh
    echo -e "\t\t\t\t----------------------------------------
                                 users
                                 user [username]"
    ;;
esac
exit 0
